import test, { chromium, expect } from "@playwright/test"
test("Locators and Assertion", async({page})=>{
await page.goto("http://leaftaps.com/opentaps/control/main")
await page.locator("#username").fill("Demosalesmanager")
await page.locator("#password").fill("crmsfa")
await page.locator(".decorativeSubmit").click()
await await page.getByText('CRM/SFA').click()
await page.locator("//a[text()='Leads']").click()
await page.locator("//a[text()='Find Leads']").click()
await page.locator('input[name="firstName"]').last().fill("Akshaya")
await page.locator("//button[text()='Find Leads']").click()
await page.locator("//a[text()='Akshaya']").first().click()
await page.locator("//a[text()='Edit']").click()
await page.locator("#updateLeadForm_companyName").clear()
await page.locator("#updateLeadForm_companyName").fill("Amazon")
await page.locator("#updateLeadForm_annualRevenue").clear()
await page.locator("#updateLeadForm_annualRevenue").fill("20000")
await page.locator("#updateLeadForm_departmentName").fill("QA")
await page.locator("#updateLeadForm_description").fill("For testing purpose")
await page.locator("input[name='submitButton']").first().click()
await expect(page.locator("#viewLead_companyName_sp")).toContainText("Amazon")
await expect(page.locator("#viewLead_annualRevenue_sp")).toContainText("20,000.00")
await expect(page.locator("#viewLead_departmentName_sp")).toContainText("QA")
await expect(page.locator("#viewLead_description_sp")).toContainText("For testing purpose")

})