import test, { chromium, expect } from "@playwright/test"
test("Locators and Assertion", async()=>{
const browser = await chromium.launch({headless:false});
const context = await browser.newContext()
const page = await context.newPage()
await page.goto("http://leaftaps.com/opentaps/control/main")
await page.locator("#username").fill("Demosalesmanager")
await page.locator("#password").fill("crmsfa")
await page.locator(".decorativeSubmit").click()
await page.waitForTimeout(2000)
await await page.getByText('CRM/SFA').click()
await page.waitForTimeout(2000)
await page.locator('//a[text()="Leads"]').click()
await page.waitForTimeout(2000)
await page.getByRole('link', { name: 'Create Lead' }).click()
await page.waitForTimeout(2000)
await page.locator("#createLeadForm_companyName").fill("Myntra")
await page.locator("#createLeadForm_firstName").fill("Akshaya")
await page.locator("#createLeadForm_lastName").fill("Narasiman")
await page.locator("#createLeadForm_personalTitle").fill("Dear")
await page.locator("#createLeadForm_generalProfTitle").fill("Mrs")
await page.locator("#createLeadForm_annualRevenue").fill("80000")
await page.locator("#createLeadForm_departmentName").fill("Engineering")
await page.locator("#createLeadForm_primaryPhoneNumber").fill("9176734288")
await page.waitForTimeout(4000)
await page.locator(".smallSubmit").evaluate(element => element.scrollIntoView())
await page.locator(".smallSubmit").click()
await page.waitForTimeout(3000)
await expect(page.locator("#viewLead_companyName_sp")).toContainText("Myntra")
await expect(page.locator("#viewLead_firstName_sp")).toContainText("Akshaya")
await expect(page.locator("#viewLead_lastName_sp")).toHaveText("Narasiman")
const isStatusVisible= await page.locator("//span[text()='Status']").isVisible()
await expect(isStatusVisible).toBeTruthy()

})